// Re-export all Note-related types from shared/types
export type {
  Note,
  NoteInput,
  NoteGetAllOptions,
  NoteSearchFilter,
  Notebook,
  NotebookStatus,
  NotebookInput,
  NotebookFolder,
  NotebookFolderTreeNode,
  NotebookFolderCreateInput,
  NotebookFolderCreateResponse,
  NotebookFolderRenameInput,
  NotebookFolderRenameResponse,
  NotebookFolderDeleteInput,
  NotebookFolderDeleteResponse,
  NotebookFolderErrorCode,
  LocalFolderTreeNode,
  LocalFolderFileEntry,
  LocalFolderNotebookMount,
  LocalFolderFileContent,
  LocalFolderFileErrorCode,
  LocalFolderCreateFileInput,
  LocalFolderCreateFileResponse,
  LocalFolderCreateFolderInput,
  LocalFolderCreateFolderResponse,
  LocalFolderDeleteEntryInput,
  LocalFolderAnalyzeDeleteResponse,
  LocalFolderDeleteEntryResponse,
  LocalFolderRenameEntryInput,
  LocalFolderRenameEntryResponse,
  LocalFolderSearchInput,
  LocalFolderSearchResponse,
  LocalFolderSearchHit,
  LocalNoteMetadata,
  LocalFolderListNoteMetadataResponse,
  LocalFolderUpdateNoteMetadataInput,
  LocalFolderUpdateNoteMetadataResponse,
  LocalFolderRelinkInput,
  LocalFolderRelinkResponse,
  LocalFolderWatchEvent,
  LocalFolderAffectedMount,
  LocalFolderTreeResult,
  Tag,
  TagWithSource,
  NoteTag,
  NoteLink,
  SmartViewId
} from '../../../shared/types'

// Re-export constants
export { RECENT_DAYS } from '../../../shared/types'
